### ISSUE TITLE
Navbar layout changes after clicking hamburger

### ISSUE THREAD

**Issue by nichandy** [amberwave/amberwave.io#1]
***Reproduction***
Start on mobile display when hamburger dropdown is visible. Open browser display size debugger. Click on the hamburger to open dropdown. While open make display larger. 

***Problem***
The dropdown either disappears or stays in stacked instead of becoming inline with the navbar.

***Possible Solutions***
Target the js click action to only fire on certain elements when display size conditions are met.

**Comment by reconchris** [comment]
Let me know when you want to zoom nick. I am avalialbe durring the weekends or around 1pm durring my lunch-Chris

    On Sunday, September 27, 2020, 2:50:10 PM PDT, Nicholas Handy <notifications@github.com> wrote:  
 
 


Reproduction
Start on mobile display when hamburger dropdown is visible. Open browser display size debugger. Click on the hamburger to open dropdown. While open make display larger.

Problem
The dropdown either disappears or stays in stacked instead of becoming inline with the navbar.

Possible Solutions
Target the js click action to only fire on certain elements when display size conditions are met.

**Comment by nichandy** [comment]
Frontend is being revised using react. For now this is not longer an issue.
